platform :ios, '12.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'KakaoSDKCommon', ‘2.11.3’
  pod 'KakaoSDKAuth', ‘2.11.3’
  pod 'KakaoSDKUser', ‘2.11.3’
  pod 'KakaoSDKTalk', ‘2.11.3’
  pod 'KakaoSDKShare', ‘2.11.3’
  pod 'KakaoSDKTemplate', ‘2.11.3’
  
  
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end
